<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Post extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Post_model');
    } 

    /*
     * Listing of posts
     */
    function index()
    {
        $data['posts'] = $this->Post_model->get_all_posts();
        
        $data['_view'] = 'post/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new post
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('title','Title','required');
		$this->form_validation->set_rules('content','Content','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'title' => $this->input->post('title'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
				'content' => $this->input->post('content'),
            );
            
            $post_id = $this->Post_model->add_post($params);
            redirect('post/index');
        }
        else
        {
			$this->load->model('User_model');
			$data['all_users'] = $this->User_model->get_all_users();
            
            $data['_view'] = 'post/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a post
     */
    function edit($id)
    {   
        // check if the post exists before trying to edit it
        $data['post'] = $this->Post_model->get_post($id);
        
        if(isset($data['post']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('title','Title','required');
			$this->form_validation->set_rules('content','Content','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'title' => $this->input->post('title'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
					'content' => $this->input->post('content'),
                );

                $this->Post_model->update_post($id,$params);            
                redirect('post/index');
            }
            else
            {
				$this->load->model('User_model');
				$data['all_users'] = $this->User_model->get_all_users();

                $data['_view'] = 'post/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The post you are trying to edit does not exist.');
    } 

    /*
     * Deleting post
     */
    function remove($id)
    {
        $post = $this->Post_model->get_post($id);

        // check if the post exists before trying to delete it
        if(isset($post['id']))
        {
            $this->Post_model->delete_post($id);
            redirect('post/index');
        }
        else
            show_error('The post you are trying to delete does not exist.');
    }
    
}
